name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
      
      - name: install sass
        run:
          sudo npm install -g sass pleeease-cli

      - name: build sass
        run:
          sass scss:dist/css

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Sass build
